# Generated by Django 3.0.3 on 2020-05-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TargetTempLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField()),
                ('date', models.DateField()),
                ('target_temp', models.DecimalField(decimal_places=1, max_digits=3)),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WindLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField()),
                ('date', models.DateField()),
                ('wind', models.CharField(max_length=10)),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CommonLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField()),
                ('date', models.DateField()),
                ('detail_num', models.IntegerField(default=0)),
                ('total_money', models.IntegerField(default=0)),
                ('reach_target_times', models.IntegerField(default=0)),
                ('scheduled_times', models.IntegerField(default=0)),
                ('ac_use_times', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('room_id', 'date')},
            },
        ),
    ]
