# Generated by Django 3.0.3 on 2020-04-17 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomstatus',
            name='electricity_now',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='roomstatus',
            name='online_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
