# Generated by Django 3.0.3 on 2020-05-27 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='targettemplog',
            unique_together={('room_id', 'date', 'target_temp')},
        ),
        migrations.AlterUniqueTogether(
            name='windlog',
            unique_together={('room_id', 'date', 'wind')},
        ),
    ]
