# Generated by Django 3.0.3 on 2020-04-18 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200417_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomstatus',
            name='electricity_now',
        ),
    ]
