# Generated by Django 3.0.3 on 2020-04-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_roomstatus_electricity_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomstatus',
            name='electricity_now',
            field=models.IntegerField(default=0),
        ),
    ]
