# Generated by Django 3.0.6 on 2020-06-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200527_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonlog',
            name='change_temp_times',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commonlog',
            name='change_wind_times',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commonlog',
            name='online_time',
            field=models.IntegerField(default=0),
        ),
    ]
