# Generated by Django 3.0.6 on 2020-06-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200609_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonlog',
            name='total_money',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
