# Generated by Django 3.0.6 on 2020-06-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20200626_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonlog',
            name='total_money',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='targettemplog',
            name='target_temp',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
