# Generated by Django 3.0.6 on 2020-06-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20200626_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonlog',
            name='total_money',
            field=models.FloatField(default=0),
        ),
    ]
